### ISSUE TITLE
Plugin files serving does not check the cohort membership

### ISSUE THREAD

**Issue by mudrd8mz** [moodleuulm/moodle-block_cohortspecifichtml#1]
Do I read it right that the function `block_cohortspecifichtml_pluginfile()` does not check the user's cohort? I agree it is quite an edge case but ideally, it should respect the same access rules as the `block_cohortspecifichtml::get_content()`.

**Comment by Kathrin84** [comment]
Hi @mudrd8mz,
thanks for this hint - this is a valid one.

Unfortunately I have problems to check the conditions in `block_cohortspecifichtml::get_content()`, because there I don't have the block instance as a passed parameter. 
In my functions in which I check all the permissions, if a user should see the content, I'm passing a `block_cohortspecifichtml instance`.

In the pluginfile function I've only got an `$birecordorcm block instance record`and I did not find any function in Moodle to get the block instance out of this database record.

Do you have a hint for me how I could proceed. The lib/blocklib was not helpful for me. Do you know a solution or maybe have workaround in mind? 

Best, Kathrin

**Comment by mudrd8mz** [comment]
Without looking into actual details, I would suggest to check how `block_html_pluginfile()` does these things.

> I've only got an $birecordorcm block instance recordand I did not find any function in Moodle to get the block instance out of this database record

Is not `block_instance()` doing it? (taking the DB record as the second parameter).

**Comment by Kathrin84** [comment]
Hi David,
thanks for the hint with the full record as the second parameter. I've tried several possibilities with the funktion `block_instance`, but this one I did not...
Here's the patch for this issue: https://github.com/moodleuulm/moodle-block_cohortspecifichtml/commit/f866cb12f0b7beef3a53744fbd48bf59fadcedf0
So I'll close this issue.
Best, Kathrin

**Comment by mudrd8mz** [comment]
Nice! Thanks a lot.
