### ISSUE TITLE
Display Images

### ISSUE THREAD

**Issue by johnpap21** [moodleuulm/moodle-block_cohortspecifichtml#3]
Hello

I use the Theme Lambda theme, and I have found that imported images will not show up in the block.

Can you assist please?

Regards
John

**Comment by abias** [comment]
Hi John,

could you please cross-check if your "imported images" appear when you switch to the Boost theme?

If yes, please turn to the developer of the Lambda Theme as we can't support problems with third-party themes (see https://github.com/moodleuulm/moodle-block_cohortspecifichtml/blob/master/README.md#theme-support).

If no, please provide steps to reproduce (see https://docs.moodle.org/37/en/How_to_add_steps_to_reproduce_to_a_bug_report) so that we see what exactly you are doing to import images into the block.

Thanks,
Alex

**Comment by Kathrin84** [comment]
Hi @johnpap21,

I've just wanted to ask if this is still an issue of yours as you did not provide some further information. Otherwise we would close this issue.

Best, Kathrin

**Comment by Kathrin84** [comment]
As there was no further feedback since, I close this issue at this point.
